import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { ThemeProvider } from "next-themes";
import { FontProvider, useFontContext } from "@/providers/FontProvider";
import Nav from "@/components/Nav";
import SearchBar from "@/components/SearchBar";
import { Suspense } from "react";
import Loading from "./loading";
import { Providers } from "@/store/Providers";

export const metadata: Metadata = {
  title: "Dictionary Mimms App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <FontProvider>
        <body suppressHydrationWarning
          className={`lg:max-w-[737px] w-full lg:m-auto px-6 lg:px-6 md:px-[39px] dark:bg-[#050505] bg-white dark:text-white text-[#050505] md:m-0`}
        >
          <Providers>
          <ThemeProvider  >

            <Nav  />
            <SearchBar /> 
            {children}

          </ThemeProvider>
          </Providers>
        </body>
      </FontProvider>
    </html>
  );
}
